policy_name: hybrid
policies:
- policy_name: pred_darts_utility
  policy_params:
    util_type: latency
    mdc_percentile: 99
    method: cobyla
    processing_time: 180
    cluster_processing_times: !include ../cluster_processing_time.yaml
    aggregator: none
    upscale_overhead: 65
    window_size_s: 420
    resource_limit: !include resources_limit.yaml
    min_max: 3
    adjust: true
    individually: false
    latency_estimator: max
    model_params: !include ../nhits_model.yaml
  autoscale_config: !include ../pred_autoscale_config.yaml
- policy_name: ai
  autoscale_config: !include ../autoscale_config.yaml
clusters: !include ../cluster_specs.yaml
unit_time: 60
