apiVersion: v1
kind: Pod
metadata:
  name: loadgen
  labels:
    name: loadgen
spec:
  containers:
  - name: loadgen
    image: beomyeol/ray-pytorch:1.10
    command: ["/bin/bash", "-c", "--"]
    args: ['trap : TERM INT; sleep infinity & wait;']
    resources:
      requests:
        memory: "4Gi"
        cpu: "2000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
        # memory: "512Mi"
        # cpu: "2000m"
