
- name: serve-cluster0
  worker: !include job_resources_specs.yaml
  min_workers: 1
  idle_timeout_s: 30
- name: serve-cluster1
  worker: !include job_resources_specs.yaml
  min_workers: 1
  idle_timeout_s: 30
- name: serve-cluster2
  worker: !include job_resources_specs.yaml
  min_workers: 1
  idle_timeout_s: 30
- name: serve-cluster3
  worker: !include job_resources_specs.yaml
  min_workers: 1
  idle_timeout_s: 30
- name: serve-cluster4
  worker: !include job_resources_specs.yaml
  min_workers: 1
  idle_timeout_s: 30
- name: serve-cluster5
  worker: !include job_resources_specs.yaml
  min_workers: 1
  idle_timeout_s: 30
- name: serve-cluster6
  worker: !include job_resources_specs.yaml
  min_workers: 1
  idle_timeout_s: 30
- name: serve-cluster7
  worker: !include job_resources_specs.yaml
  min_workers: 1
  idle_timeout_s: 30
- name: serve-cluster8
  worker: !include job_resources_specs.yaml
  min_workers: 1
  idle_timeout_s: 30
- name: serve-cluster9
  worker: !include job_resources_specs.yaml
  min_workers: 1
  idle_timeout_s: 30
